package filter

// Code generated from ntx-packages/libs/core/src/utils/common.util.ts
// (MySqlError + PostgresError merged into SqlError). DO NOT EDIT BY HAND —
// regenerate from the TS source if it changes. Mirrors TS getSqlError().

import "fmt"

// sqlErrorFallback mirrors the TS getSqlError() fallback string.
const sqlErrorFallback = "Check your request and try again, something is not quite right with it"

// sqlErrors maps a MySQL errno (numeric, as string) or PostgreSQL SQLSTATE code
// to a friendly, user-facing message. Merged from MySqlError + PostgresError to
// mirror TS SqlError = { ...MySqlError, ...PostgresError }.
var sqlErrors = map[string]string{
	"1040": "The server is currently overloaded and cannot accept new connections. Please try again later.",
	"1042": "Unable to connect to the database server. Please check your connection settings and try again.",
	"1043": "Invalid connection handle. Please verify your database connection and try again.",
	"1050": "The table already exists in the database.",
	"1062": "The provided value already exists. Please choose a different value.",
	"1064": "There is an error in your SQL syntax. Please check your query and try again.",
	"1067": "Invalid default value for the column. Please provide a valid default value.",
	"1072": "The specified key column is used more than once. Please ensure each key column is unique.",
	"1146": "The table does not exist in the database.",
	"1205": "The operation exceeded the maximum time allowed. Please try again later.",
	"1213": "A deadlock was detected. Please retry the transaction.",
	"1216": "Cannot add or update a child row without a matching parent row. Please check your data.",
	"1217": "Cannot delete or update a parent row that has dependent child rows. Please remove the dependent child rows first.",
	"1227": "Access denied. Please check your permissions and try again.",
	"1235": "This version of MySQL is not supported. Please upgrade to a supported version.",
	"1241": "The operand should contain only one column. Please provide a single column value.",
	"1242": "The subquery returned more than one row. Please ensure the subquery returns a single row.",
	"1251": "The client does not support the requested authentication protocol. Please upgrade your client.",
	"1265": "The data provided is too large and has been truncated. Please reduce the data size.",
	"1364": "The field value cannot be empty. Please provide a valid value.",
	"1406": "The data provided is too long for the column. Please shorten the data length.",
	"1451": "Cannot delete or update a parent row: a foreign key constraint fails. Please check the dependencies.",
	"1452": "Cannot add or update a child row: a foreign key constraint fails. Please check the parent row.",
	"20000": "No matching option found for your selection. Please choose a valid option.",
	"21000": "Your request returned multiple results where only one was expected. Please refine your criteria.",
	"22000": "There is a problem with the data you provided. Please review and correct it.",
	"22001": "The text you entered is too long. Please shorten it and try again.",
	"22002": "A required value is missing. Please fill in all required fields.",
	"22003": "The number is too large or too small. Please enter a value within the allowed range.",
	"22004": "This field cannot be empty. Please provide a value.",
	"22005": "The value cannot be assigned to this field. Please check the field type.",
	"22007": "Invalid date or time format. Please use the correct format (e.g., YYYY-MM-DD).",
	"22008": "The date or time value is outside the valid range. Please enter a valid date/time.",
	"22009": "Invalid timezone. Please select a valid timezone.",
	"22010": "Invalid indicator value provided. Please check your input.",
	"22011": "Invalid text operation. Please check your input parameters.",
	"22012": "Cannot divide by zero. Please provide a non-zero value.",
	"22013": "Invalid range specified. Please provide valid start and end values.",
	"22014": "Invalid value provided for data partitioning. Please use a positive number.",
	"22015": "The time interval is too large. Please use a smaller duration.",
	"22016": "Invalid position specified for data retrieval. Please use a valid position.",
	"22018": "Cannot convert this value to the required format. Please check the data type.",
	"22019": "Invalid special character detected. Please check your input.",
	"22021": "The text contains characters that are not supported. Please remove special characters.",
	"22022": "A numeric indicator exceeded its allowed range.",
	"22023": "One or more values are invalid. Please review your input and try again.",
	"22024": "Text contains invalid termination. Please remove special characters.",
	"22025": "Invalid character sequence detected. Please check for special characters.",
	"22026": "The text length does not match the expected size. Please adjust your input.",
	"22027": "Unable to trim the text as specified. Please check your input.",
	"22030": "Duplicate keys found in JSON. Each key must be unique.",
	"22031": "Invalid date/time in JSON. Please use the correct format.",
	"22032": "The JSON format is invalid. Please check for syntax errors.",
	"22033": "Invalid JSON path specified. Please check the path syntax.",
	"22034": "Multiple values found where only one was expected. Please refine your query.",
	"22035": "No matching JSON element found. Please check the path.",
	"22036": "Expected a number but found a different type. Please provide a numeric value.",
	"22037": "Duplicate keys found in JSON object. Please ensure all keys are unique.",
	"22038": "Expected a single JSON value but found multiple. Please refine your selection.",
	"22039": "The specified JSON array was not found. Please check the path.",
	"23000": "This change would violate data integrity rules. Please review your input.",
	"23001": "This action is restricted. The item may be referenced elsewhere.",
	"23502": "This field is required. Please provide a value before saving.",
	"23503": "This item references another record that does not exist. Please check related data.",
	"23505": "This value already exists. Please choose a different value.",
	"23514": "The value does not meet the required criteria. Please check the requirements.",
	"24000": "Unable to navigate the results. Please refresh and try again.",
	"25000": "The operation cannot be completed in the current state. Please try again.",
	"25001": "Another operation is already in progress. Please wait for it to complete.",
	"25002": "A related operation is already running. Please wait and try again.",
	"25003": "This operation is not allowed in the current mode. Please try a different approach.",
	"25004": "This operation requires different isolation settings. Please contact support.",
	"25005": "No active operation to complete. Please start a new request.",
	"25006": "Cannot make changes in read-only mode. Please contact your administrator.",
	"25007": "Cannot mix structure changes with data changes. Please separate these operations.",
	"25008": "Session settings have changed. Please refresh and retry.",
	"26000": "The requested operation does not exist. Please check your request.",
	"27000": "An automated rule prevented this change. Please review your data.",
	"28000": "Authentication failed. Please check your credentials and try again.",
	"34000": "The result set reference is invalid. Please refresh and try again.",
	"38000": "An external process encountered an error. Please try again later.",
	"38001": "The external process cannot execute database commands.",
	"38002": "The external process cannot modify data.",
	"38003": "The external process attempted a forbidden operation.",
	"38004": "The external process cannot read data.",
	"39000": "Failed to call an external process. Please try again.",
	"39001": "The external process returned an unexpected status.",
	"39004": "The external process received an empty value where one was required.",
	"40000": "Your changes could not be saved and have been reverted. Please try again.",
	"40001": "A conflict with another user occurred. Please try again.",
	"40002": "Your changes would violate data rules and have been reverted.",
	"40003": "Unable to confirm if your changes were saved. Please verify and retry if needed.",
	"42000": "There is an error in your request. Please check and try again.",
	"42501": "You do not have permission to perform this action. Please contact your administrator.",
	"42601": "Your request contains a syntax error. Please review and correct it.",
	"42602": "Invalid name format. Please use only allowed characters.",
	"42611": "Invalid field definition. Please check the settings.",
	"42622": "The name is too long. Please use a shorter name.",
	"42701": "A field with this name already exists. Please use a different name.",
	"42702": "The field name is ambiguous. Please specify which one you mean.",
	"42703": "The specified field does not exist. Please check the field name.",
	"42704": "The specified item does not exist. Please check the name.",
	"42710": "An item with this name already exists. Please use a different name.",
	"42712": "An alias with this name already exists. Please use a different name.",
	"42723": "A function with this name already exists. Please use a different name.",
	"42725": "The operation name is ambiguous. Please be more specific.",
	"42803": "Invalid grouping in your request. Please review and correct it.",
	"42804": "Data types do not match. Please ensure values are compatible.",
	"42809": "Wrong type of object specified. Please check your reference.",
	"42830": "Invalid relationship reference. Please check the related data.",
	"42846": "Cannot convert between these data types. Please check your values.",
	"42883": "The requested operation does not exist. Please check your request.",
	"42939": "This name is reserved and cannot be used. Please choose a different name.",
	"44000": "This change would create data that violates view rules. Please adjust your input.",
	"53000": "The server is running low on resources. Please try again later.",
	"53100": "The server has run out of storage space. Please contact support.",
	"53200": "The server has run out of memory. Please try again later or reduce your request size.",
	"53300": "The server is too busy right now. Please try again in a few moments.",
	"53400": "A system limit has been reached. Please contact support.",
	"54000": "Your request exceeds system limits. Please simplify and try again.",
	"54001": "Your request is too complex. Please break it into smaller parts.",
	"54011": "Too many fields specified. Please reduce the number of fields.",
	"54023": "Too many values provided. Please reduce the number of items.",
	"55000": "The item is not in the required state for this operation. Please try again.",
	"55006": "This item is currently in use. Please try again later.",
	"57000": "The server is undergoing maintenance. Please try again later.",
	"57014": "Your request was cancelled. Please try again if needed.",
	"58000": "A system error occurred. Please try again or contact support.",
	"58030": "A file system error occurred. Please try again or contact support.",
	"72000": "The data snapshot is too old. Please refresh and try again.",
	"00000": "Your request was completed successfully.",
	"01000": "Your request completed with a warning. Please review the results carefully.",
	"0100C": "Your request returned multiple result sets. Please check that you received all expected data.",
	"01008": "Some data was automatically padded to fit the required format.",
	"01003": "Empty values were excluded from the calculation. Your results may differ from expected.",
	"01007": "The permission could not be granted. Please contact your administrator.",
	"01006": "The permission could not be removed. Please contact your administrator.",
	"01004": "Some text was shortened to fit the allowed length. Please check your data.",
	"01P01": "This feature will be removed in a future update. Please update your request.",
	"02000": "No matching records found. Please try different search criteria.",
	"02001": "No additional results are available.",
	"03000": "Your request is still being processed. Please wait and try again.",
	"08000": "Unable to connect to the server. Please check your internet connection and try again.",
	"08003": "Your session has ended. Please refresh the page or log in again.",
	"08006": "Lost connection to the server. Please check your internet and try again.",
	"08001": "Cannot reach the server right now. Please try again in a few moments.",
	"08004": "Connection was refused. Please verify your credentials and try again.",
	"08007": "Connection was interrupted during processing. Your changes may not have been saved.",
	"08P01": "Communication error with the server. Please refresh and try again.",
	"09000": "An automated process encountered an error. Please contact support if this persists.",
	"0A000": "This feature is not available. Please try a different approach or contact support.",
	"0B000": "Unable to start this operation. Please try again or contact support.",
	"0F000": "Unable to locate the requested resource. Please verify your request.",
	"0F001": "The reference you provided is invalid. Please check and try again.",
	"0L000": "You cannot grant this permission. Please contact your administrator.",
	"0LP01": "This permission change is not allowed. Please contact your administrator.",
	"0P000": "The specified role does not exist or is invalid. Please check your selection.",
	"0Z000": "Unable to retrieve error details. Please try again or contact support.",
	"0Z002": "Unable to access diagnostic information. Please contact support.",
	"2202E": "The list position you specified is out of range. Please use a valid position.",
	"2200B": "There is a conflict with special characters. Please check your input.",
	"2201E": "Cannot calculate logarithm of zero or negative numbers. Please provide a positive value.",
	"2201F": "Invalid values for power calculation. Please check your numbers.",
	"2201G": "Invalid parameters for data bucketing. Please review your values.",
	"2200D": "Invalid character encoding detected. Please use standard characters.",
	"22P06": "Non-standard character usage detected. Please use standard formatting.",
	"2201B": "Invalid search pattern. Please check your search text for special characters.",
	"2201W": "Invalid limit specified. Please use a positive number.",
	"2201X": "Invalid offset specified. Please use a non-negative number.",
	"2202H": "Invalid sample size specified. Please use a value between 0 and 100.",
	"2202G": "Invalid sample repeat value. Please provide a valid number.",
	"2200C": "Incorrect use of special characters. Please review your input.",
	"2200G": "Data type mismatch detected. Please ensure all values match the expected type.",
	"2200H": "The maximum allowed sequence value has been reached. Please contact support.",
	"2200F": "Empty text is not allowed. Please provide a value.",
	"22P01": "A calculation error occurred. Please check your numeric values.",
	"22P02": "The text format is invalid. Please check your input format.",
	"22P03": "The data format is invalid. Please provide correctly formatted data.",
	"22P04": "The file format is incorrect. Please use the correct format.",
	"22P05": "The text contains characters that cannot be converted. Please use standard characters.",
	"2200L": "The provided content is not valid XML. Please check the format.",
	"2200M": "The XML document is malformed. Please verify the XML structure.",
	"2200N": "The XML content is invalid. Please check for errors.",
	"2200S": "The XML comment is invalid. Please fix the XML format.",
	"2200T": "The XML processing instruction is invalid. Please check the XML.",
	"2203A": "The specified JSON property was not found. Please verify the property name.",
	"2203B": "Expected a JSON number but found a different type.",
	"2203C": "The specified JSON object was not found. Please check the path.",
	"2203D": "Too many items in the JSON array. Please reduce the number of items.",
	"2203E": "Too many properties in the JSON object. Please reduce the complexity.",
	"2203F": "Expected a simple JSON value (string, number, boolean). Please check your data.",
	"23P01": "This value conflicts with an existing record. Please use a different value.",
	"25P01": "No operation in progress. Please start a new request.",
	"25P02": "The previous operation failed. Please start fresh and try again.",
	"25P03": "Your session timed out due to inactivity. Please refresh and try again.",
	"28P01": "Incorrect password. Please try again or reset your password.",
	"2B000": "Cannot remove permissions while they are still in use.",
	"2BP01": "Cannot delete this item because other items depend on it. Please remove dependencies first.",
	"2D000": "Unable to complete the operation. Please try again.",
	"2F000": "An error occurred while processing your request. Please try again.",
	"2F005": "The operation did not produce the expected result. Please contact support.",
	"2F002": "This operation cannot modify data in the current context.",
	"2F003": "This operation is not permitted. Please try a different approach.",
	"2F004": "This operation cannot read data in the current context.",
	"39P01": "An automated trigger encountered an error. Please contact support.",
	"39P02": "A data processing function encountered an error. Please contact support.",
	"39P03": "An event handler encountered an error. Please contact support.",
	"3B000": "Unable to create a restore point. Please try again.",
	"3B001": "Invalid restore point reference. Please check your request.",
	"3D000": "The specified database does not exist. Please check the name.",
	"3F000": "The specified schema does not exist. Please check the name.",
	"40P01": "A conflict with another operation was detected. Please wait a moment and try again.",
	"42P20": "Invalid window operation. Please check your request.",
	"42P19": "Invalid recursive reference. Please review your request structure.",
	"42P18": "Unable to determine the data type. Please be more specific.",
	"42P21": "Incompatible text sorting rules. Please check your settings.",
	"42P22": "Unable to determine text sorting rules. Please be more specific.",
	"428C9": "This value is auto-generated and cannot be changed.",
	"42P01": "The specified table does not exist. Please check the name.",
	"42P02": "Missing required parameter. Please provide all required values.",
	"42P03": "A cursor with this name already exists.",
	"42P04": "A database with this name already exists. Please use a different name.",
	"42P05": "A statement with this name already exists.",
	"42P06": "A schema with this name already exists. Please use a different name.",
	"42P07": "A table with this name already exists. Please use a different name.",
	"42P08": "The parameter name is ambiguous. Please be more specific.",
	"42P09": "The alias is ambiguous. Please use a unique name.",
	"42P10": "Invalid field reference. Please check the field name.",
	"42P11": "Invalid cursor definition. Please check your request.",
	"42P12": "Invalid database definition. Please check the settings.",
	"42P13": "Invalid function definition. Please check the settings.",
	"42P14": "Invalid statement definition. Please check your request.",
	"42P15": "Invalid schema definition. Please check the settings.",
	"42P16": "Invalid table definition. Please check the settings.",
	"42P17": "Invalid object definition. Please check the settings.",
	"55P02": "Cannot change this setting during operation. Please try later.",
	"55P03": "Unable to acquire lock. Another process is using this resource. Please try again.",
	"55P04": "Cannot use new values until the current operation completes.",
	"57P01": "The server is shutting down for maintenance. Please try again later.",
	"57P02": "The server experienced an unexpected shutdown. Please try again.",
	"57P03": "The server is starting up. Please wait a moment and try again.",
	"57P04": "The database has been removed. Please contact your administrator.",
	"57P05": "Your session timed out due to inactivity. Please refresh and log in again.",
	"58P01": "A required file could not be found. Please contact support.",
	"58P02": "A file conflict was detected. Please contact support.",
	"F0000": "A configuration error occurred. Please contact support.",
	"F0001": "The server lock file already exists. Please contact support.",
	"HV000": "An error occurred connecting to external data. Please try again.",
	"HV005": "The specified column was not found in the external data source.",
	"HV002": "Missing required connection parameter. Please check your settings.",
	"HV010": "External data operations performed in wrong order. Please try again.",
	"HV021": "External data configuration is inconsistent. Please contact support.",
	"HV024": "Invalid value for external data attribute. Please check your settings.",
	"HV007": "Invalid column name in external data. Please check the name.",
	"HV008": "Invalid column number in external data. Please check your reference.",
	"HV004": "Unsupported data type in external source. Please contact support.",
	"HV006": "Invalid data type configuration. Please contact support.",
	"HV091": "Invalid external data descriptor. Please contact support.",
	"HV00B": "Invalid external data handle. Please reconnect and try again.",
	"HV00C": "Invalid option index for external data. Please contact support.",
	"HV00D": "Unknown option name for external data. Please check your settings.",
	"HV090": "Invalid text length for external data. Please check your input.",
	"HV00A": "Invalid text format for external data. Please check your input.",
	"HV009": "Missing required value for external data operation.",
	"HV014": "Too many external data connections. Please close some and try again.",
	"HV001": "External data system ran out of memory. Please try again later.",
	"HV00P": "No schemas found in external data source.",
	"HV00J": "Unknown option specified for external data. Please check your settings.",
	"HV00K": "Error processing external data response.",
	"HV00Q": "Schema not found in external data source. Please check the name.",
	"HV00R": "Table not found in external data source. Please check the name.",
	"HV00L": "Cannot create external data connection. Please check your settings.",
	"HV00M": "Cannot process external data response. Please try again.",
	"HV00N": "Cannot connect to external data source. Please check connection settings.",
	"P0000": "A database procedure encountered an error. Please try again or contact support.",
	"P0001": "A custom error occurred. Please check the details and try again.",
	"P0002": "The requested data was not found. Please check your criteria.",
	"P0003": "Multiple records found where only one was expected. Please refine your search.",
	"P0004": "A validation check failed. Please review your data and try again.",
	"XX000": "An unexpected internal error occurred. Please try again or contact support.",
	"XX001": "Data integrity issue detected. Please contact support immediately.",
	"XX002": "Index integrity issue detected. Please contact support immediately.",
}

// GetSQLError mirrors TS getSqlError(errnoOrCode): it stringifies the code and
// returns the mapped friendly message, or the fallback when the code is unknown.
func GetSQLError(errnoOrCode any) string {
	key := fmt.Sprintf("%v", errnoOrCode)
	if msg, ok := sqlErrors[key]; ok {
		return msg
	}
	return sqlErrorFallback
}
